-- Banco privado de interessados. O navegador nunca acessa esta tabela diretamente.
create table if not exists public.requests (
  id bigint generated by default as identity primary key,
  name varchar(80) not null check (char_length(name) between 1 and 80),
  contact_type text not null default 'telegram' check (contact_type = 'telegram'),
  contact_value varchar(120) not null check (char_length(contact_value) between 5 and 120),
  choice varchar(120) not null check (choice in (
    'Avaliação — R$ 10,00',
    'Vídeo personalizado',
    'Videochamada — R$ 99,00 / 10 min',
    'Privacidade — Acesso aos dados',
    'Privacidade — Correção de dados',
    'Privacidade — Exclusão de dados'
  )),
  custom_details varchar(500) not null default '' check (
    custom_details = '' or choice like 'Privacidade — %'
  ),
  workflow_status text not null default 'novo' check (workflow_status in (
    'novo', 'contato_iniciado', 'aguardando_pagamento', 'confirmado', 'concluido', 'recusado'
  )),
  consent_at timestamptz not null default now(),
  privacy_version varchar(20) not null,
  rules_accepted_at timestamptz,
  rules_version varchar(20),
  admin_notes varchar(1000) not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists requests_created_at_idx on public.requests (created_at desc);
create index if not exists requests_contact_choice_idx on public.requests (lower(contact_value), choice, created_at desc);
create index if not exists requests_status_idx on public.requests (workflow_status, updated_at);

-- RLS sem políticas públicas: somente a função do servidor com a chave secreta acessa os dados.
alter table public.requests enable row level security;
revoke all on table public.requests from anon, authenticated;
revoke all on sequence public.requests_id_seq from anon, authenticated;
grant all on table public.requests to service_role;
grant all on sequence public.requests_id_seq to service_role;
